name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Empêche les déploiements concurrents
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job 1: Build du frontend
  build:
    runs-on: ubuntu-latest
    
      - name: 📦 Installer les dépendances
        working-directory: ./frontend
        run: npm ci
      
      - name: 🔨 Build de production
        working-directory: ./frontend
        run: npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          CI: false
      